src/Binovo/ElkarBackupBundle/Resources/translations/BinovoElkarBackup.en.yml, src/Binovo/ElkarBackupBundle/Resources/translations/BinovoElkarBackup.es.yml, src/Binovo/ElkarBackupBundle/Resources/translations/BinovoElkarBackup.eu.yml
Small fix for issue #113 : added < /p > at the end of one sentence in each of the three translation files
=> Small fix for issue #113

app/DoctrineMigrations/Version20151221140149.php, src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Entity/Client.php, src/Binovo/ElkarBackupBundle/Entity/User.php, src/Binovo/ElkarBackupBundle/Form/Type/ClientType.php, src/Binovo/ElkarBackupBundle/Form/Type/UserType.php, src/Binovo/ElkarBackupBundle/Menu/Builder.php, src/Binovo/ElkarBackupBundle/Resources/public/css/elkarbackup.css, src/Binovo/ElkarBackupBundle/Resources/views/Default/client.html.twig
I just end up with a new multiuser feature for elkarbackup, check the code and let me know.
This PR adds the following capabilities.
1.- Different User roles on creation
2.- Limited users can only manage their own clients
3.- Admin users can manage any client
4.- Admin users can change the ownership of any client
;)
=> multiuser feature

src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js, src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig
We change a few files and create the clone functionality for clients with their jobs.
=> Client Clone function for elkarbackup #10

src/Binovo/ElkarBackupBundle/Form/Type/ClientType.php, src/Binovo/ElkarBackupBundle/Resources/views/Default/client.html.twig
- Bugfix: SSH args field is not required
- Improvement: show "Advanced" configuration TitlePane closed by default
=> Client configuration: SSH args not required

src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Form/Type/ClientType.php, src/Binovo/ElkarBackupBundle/Resources/public/css/elkarbackup.css, src/Binovo/ElkarBackupBundle/Resources/public/js/base.js, src/Binovo/ElkarBackupBundle/Resources/public/js/edit-client.js, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js, src/Binovo/ElkarBackupBundle/Resources/views/Default/client.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig
Removed ssh-copy-key feature
Added abort job warning modal
=> Removed ssh-copy-key feature and add abort job warning modal

app/DoctrineMigrations/Version20160310122857.php, app/DoctrineMigrations/Version20160310174104.php, app/config/security.yml, debian/DEBIAN/control, debian/changelog, src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Entity/Client.php, src/Binovo/ElkarBackupBundle/Entity/Job.php, src/Binovo/ElkarBackupBundle/Form/Type/ClientType.php, src/Binovo/ElkarBackupBundle/Form/Type/JobType.php, src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php, src/Binovo/ElkarBackupBundle/Logger/WebUserLoggerProcessor.php, src/Binovo/ElkarBackupBundle/Resources/public/css/elkarbackup.css, src/Binovo/ElkarBackupBundle/Resources/public/js/edit-job.js, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js, src/Binovo/ElkarBackupBundle/Resources/views/Default/client.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/job.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/login.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/rsnapshotconfig.txt.twig
- Feature: Client advanced configuration, custom rsync parameters
- Feature: Job advanced configuration, token management
- Feature: Remote job execution
- Feature: Improve rsnapshot sync command output (using rsync stats)
- Feature: Rsnapshot 1.4.2 compatibility
- Bugfix: move du command back to runAllJobs function
=> Rsync custom args, remote job execution and more

app/config/security.yml, src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
This PR should fix the bug #136
=> runJobAction: require HTTPS for anonymous petitions (#136)

src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
=> Do not clone job status (fixes #148)

debian/DEBIAN/control, debian/changelog, src/Binovo/ElkarBackupBundle/Resources/views/Default/login.html.twig
=> New version 1.2.1

src/Binovo/ElkarBackupBundle/Resources/views/Default/policy.html.twig
This PR will change some hard-coded strings to be translated
=> Translated missing string (fixes #185)

app/config/config.yml, src/Binovo/ElkarBackupBundle/Entity/User.php, src/Binovo/ElkarBackupBundle/Form/Type/PreferencesType.php, src/Binovo/ElkarBackupBundle/Resources/translations/BinovoElkarBackup.de.yml
- Added german translation for ElkarBackup web UI (by @nephilim75 )
- Added german to language selection form and preferences
=> Feature: german translation (fixes #185)

src/Binovo/ElkarBackupBundle/Resources/translations/BinovoElkarBackup.de.yml
Hello
just found minor translation issues in recently added german language pack (vers. 1.2.5). Please check and review.
Kind regards
//neph
=> fixed minor language issues

src/Binovo/ElkarBackupBundle/Resources/public/js/base.js, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js
This pull request adds the following things.
- Add getContext function into javascript
- Modified clone javascript functions to add the context if they need it.
=> Add context into js

src/Binovo/ElkarBackupBundle/Resources/public/js/base.js, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js
Reverts elkarbackup/elkarbackup#222
Clone option does not work if "context" does not exist
=> Revert "Add context into js"

app/DoctrineMigrations/Version20170627172436.php, src/Binovo/ElkarBackupBundle/Entity/Client.php, src/Binovo/ElkarBackupBundle/Entity/Job.php, src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig
This PR should fix the issue #217
=> Maximum backup size (issue #217)

install/eb-installer.sh
This PR will add a universal installation script named `eb-installer.sh` under the *./install* directory.
```
Usage: ./eb-installer.sh [OPTIONS]
-v    Select ElkarBackup version you want to install
-f    Path to a customized parameters.yml configuration file
-h    Database server IP address or hostname
-u    User for login to connect to the database
-U    Admin user to create the new database
-p    Password to use when connecting to server
-P    Admin password to use when connecting with admin user
-n    Database name
-y    Assume yes mode will omit any question
-d    DEBUG mode
-I    Display this help and exit
```
- You can choose between the following versions to download:
- **latest** (default): latest stable release
- **dev**: current official elkarbackup git version
- …
=> Universal installation script

app/config/config.yml, src/Binovo/ElkarBackupBundle/Resources/public/css/bootstrap.css, src/Binovo/ElkarBackupBundle/Resources/public/js/base.js, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js, src/Binovo/ElkarBackupBundle/Resources/views/Default/base.html.twig
Fix the lack of url_prefix in some parts of the clone functions.
- Added a global url_prefix (remember we need it previously on our general parameters)
- Changed the clone js functions to fix the problem
=> General url_Prefix added

app/DoctrineMigrations/Version20170629105239.php, src/Binovo/ElkarBackupBundle/Entity/User.php
This PR changes the user email property from unique to not-unique. It fixes issue #209 
PD: the doctrine migration file also contains a pending change related to user preferences (not important)
=> User email changed to not-unique

src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php
This should fix some weird problems, where we see jobs RUNNING but we don't see how they end
Related issue: #221
=> Added flush after setStatus

install/eb-installer.sh
This PR will improve universal installer (eb-installer.sh) to configure cron automatically.
=> Script installer: cron configuration

src/Binovo/ElkarBackupBundle/Resources/public/css/elkarbackup.css, src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig
This PR changes the Status color for warning job messages.
=> Distinguise warning messages with a different color

src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig
This PR fixes the diskusage progress bar.
=> Fix diskusage progress bar

src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Resources/views/Default/client.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/job.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/script.html.twig
There were some issues in twig templates that caused errors in development mode.
=> Issue #262 solving some path issues in twig templates

src/Binovo/ElkarBackupBundle/Menu/Builder.php
Fitxed tahoe navigation bar bug that trowed and exception and did not allow to configure tahoe storage when installed. #267
=> Fixed tahoe navar bug 

src/Binovo/ElkarTahoeBundle/Utils/TahoeBackup.php
The misspelling of the variable has been fixed.
#269
=> Misspelling fixed #269

app/DoctrineMigrations/Version20180207095757.php, app/config/parameters.yml, app/config/parameters.yml.dist, debian/DEBIAN/control, install/eb-installer.sh, makepackage.sh, src/Binovo/ElkarBackupBundle/BinovoElkarBackupBundle.php, src/Binovo/ElkarBackupBundle/Command/DeleteJobBackupsCommand.php, src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Entity/BackupLocation.php, src/Binovo/ElkarBackupBundle/Entity/Client.php, src/Binovo/ElkarBackupBundle/Entity/Job.php, src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php, src/Binovo/ElkarBackupBundle/Lib/Globals.php, src/Binovo/ElkarBackupBundle/Menu/Builder.php, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js, src/Binovo/ElkarBackupBundle/Resources/views/Default/backupscriptconfig.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/client.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/directory.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/job.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/script.html.twig, src/Binovo/ElkarTahoeBundle/Utils/TahoeBackup.php
Added the functionality of managing multiple backup locations.
#149
=> Multiple backup locations #149

debian/DEBIAN/postinst
This PR solves  bug #284
The regular expression to search the username has been changed. The username will be searched in a correct and specific way.
=> Username regular expression modified

src/Binovo/ElkarBackupBundle/Resources/views/Default/backuplocation.html.twig
There was a form close without starting part.
=> Remove an bad closed form.

src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js, src/Binovo/ElkarBackupBundle/Resources/views/Default/status.html.twig
This PR solves #291. Now when trying to abort a job that is not in the queue it will show an error message.
=> Added alert message when a job is aborted and it has already finished.

src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js
This PR solves bug #290 
Added messages when a job or a client cannot be deleted, managed deletion messages.
=> Alert messages related to client and job deletions

src/Binovo/ElkarBackupBundle/Command/TickCommand.php, src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Lib/LoggingCommand.php
The following PR adds debug type logs
- Add support for debug logging
- Log selection by default: "Notices and up" (debug will be hidden)
- Mute "Nothing scheduled to run" messages (moved to DEBUG)  #341
- Mute "View xxx" log messages (moved to DEBUG)
=> Debug logs

composer.lock
=> Upgrade Symfony from 2.8.11 to 2.8.52

README.md
=> Fix documentation URLs

CHANGELOG.md, README.md, src/Binovo/ElkarBackupBundle/Resources/views/Default/login.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/policies.html.twig
This should fix security bug #419 .
Xabier, do you think you'll be able to release a new version with this fix included?
=> Fix XSS in #419 + proposed new version release

CHANGELOG.md, src/Binovo/ElkarBackupBundle/Resources/views/Default/status.html.twig
=> Add client column in status

CHANGELOG.md, app/config/config_dev.yml
Changed the delivery address of swiftmailer in developer environment from xezpeleta+eb@tknika.eus to example@example.com. Master updated
=> Changed delivery address of swiftmailer on dev environment

CHANGELOG.md, src/Binovo/ElkarBackupBundle/Entity/Job.php
postScript name consistency problem corrected. Closes issue 400
=> Name consistency corrected in Job entity

CHANGELOG.md, src/Binovo/ElkarBackupBundle/Controller/DefaultController.php, src/Binovo/ElkarBackupBundle/Resources/public/js/base.js, src/Binovo/ElkarBackupBundle/Resources/views/Default/clients.html.twig, src/Binovo/ElkarBackupBundle/Resources/views/Default/policies.html.twig
Security fix XSS in Job and Client. Closes issue #427
=> Fixed XSS in Job and Client #427

CHANGELOG.md, debian/DEBIAN/control, debian/changelog
=> v1.3.5 release preparation

composer.json, composer.lock, docker/composer.json.docker
Monolog-bundle package version 2.12.1 did not work properly with php7.3, throwed warnings like:
> Warning: count(): Parameter must be an array or an object that implements Countable in /app/elkarbackup/vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php on line 628
Updated to version 3.6
=> monolog-bundle package updated to 3.6

debian/DEBIAN/postinst
This PR adds Ubuntu 20.04 support, fixes #432 . See also updated installation notes in elkarbackup-docs/1.4
=> Ubuntu 20.04 support

src/Form/Type/UserType.php
I have taken the choiceType area out of the collection, as it is a single element it was not necessary. And I have also inserted a transformer to the choiceType to process it correctly.
This would fix issue #468
=> Remove CollectionType to embed roles' choice element. Fixes issue #468

docker/entrypoint.sh
=> Avoid errors in Docker when the database exists

docker/entrypoint.sh
Required at least for the API docs. Fixes #511
=> Fix missing assets:install

config/packages/api_platform.yaml, src/Api/DataProviders/ClientCollectionDataProvider.php, src/Api/DataProviders/JobCollectionDataProvider.php
Pagination is enabled by default, but it was not working. So it has been disabled, as it was not needed explicitly.
=> Disable pagination for collections (it was not working)

src/Api/Filter/ClientByNameFilter.php, src/Api/Filter/JobByNameFilter.php, src/Entity/Client.php, src/Entity/Job.php
Added filters to get clients and jobs by their name
=> Name filter

src/Api/DataTransformers/ClientInputDataTransformer.php
The scripts were not been removed before adding the new ones
=> Empty script's lists before adding the new ones (fixes issue #512)

src/Api/DataTransformers/ClientInputDataTransformer.php
Correction of PR #519, the script lists are emptied before adding the new ones just when the client is been updated
=> Correct PR #519

public/js/edit-job.js
=> Update token input field id (to lowercase)

src/Controller/DefaultController.php
=> Inject RequestStack service

src/Form/Type/PreferencesType.php, translations/BinovoElkarBackup.fr.yml, translations/validators.fr.yml
hi all,
I've just discovered Elkarbackup a few days ago. It matches my expectation for a web based GUI around RSYNC (that I use since years for my backups).
Here is a PR to add the French translation. It think it needs to be reviewed by another french speaker if you have one around here.
=> Add French translation

composer.json, composer.lock, symfony.lock
This PR installs the Process component, which is required to recover files directly on the source host thru a Rsync command.
=> Install Process component (fixes #543)

public/js/edit-job.js, src/Api/DataTransformers/ClientInputDataTransformer.php, src/Api/DataTransformers/JobInputDataTransformer.php, src/Api/Dto/ClientInput.php, src/Api/Dto/JobInput.php
Return and parameter types defined for client and job DTOs. Now null values are allowed for ennecessary fields. 
Also, empty string is allowed for notificationsEmail. Fixes issue #535
=> Define return and parameter types for clients and jobs (#535)

fixtures/script.sh, fixtures/scripts.yaml
Added a random script to fixtures folder to be able to create script fixtures. It is not going to be executed, so the content is not important. Fixes issue #561
=> Add script to fake fixtures (#561)

fixtures/scripts.yaml, run-tests.sh, src/Api/ScriptFileFaker.php
Directory changed to '/tmp' to be always existing and writable, fixes issue #565
=> Script fixture's script directory changed (#565)

templates/default/base.html.twig, templates/default/clients.html.twig
=> Fix asset URL
