- src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
Fixing issue #114 
· Modification: setParameter($name, $value, $from) takes a new argument $from
- this allows to properly set the message for the logger
- modified every call with the new argument
@DefaultController::manageParametersAction
@DefaultController::manageBackupsLocationAction
· Bugfix: modified the message when the parameter is not set
> Fix for issue #114

- debian/DEBIAN/conffiles
- debian/DEBIAN/control
- debian/DEBIAN/postinst
- debian/DEBIAN/postrm
- debian/changelog
- debian/etc/apache2/sites-available/elkarbackup-ssl.conf
- src/Binovo/ElkarBackupBundle/Resources/views/Default/login.html.twig
This PR will:
* Enable HTTPS access
* Force Symfony cache cleaning during the installation (rm -fR /var/cache/elkarbackup/*) to avoid errors migrating to v1.2
* Hide annoying messages during the upgrade
* Increment version number to **v1.2-Pre-Alpha3**
> HTTPS virtual host enabled

- app/SymfonyRequirements.php
- app/config/parameters.yml
- bootstrap.sh
This PR will:
* Update SymfonyRequirements.php to the last Symfony 2.8
* Modify bootstrap.sh script to create sessions directory with right permissions
* Ignore parameters.yml in Git (it will use parameters.yml.dist instead)
> Ignore parameters.yml and set right permissions for sessions directory

- app/DoctrineMigrations/Version20160103215703.php
- src/Binovo/ElkarBackupBundle/Entity/Client.php
- src/Binovo/ElkarBackupBundle/Entity/Job.php
- src/Binovo/ElkarBackupBundle/Form/Type/ClientType.php
- src/Binovo/ElkarBackupBundle/Resources/public/css/elkarbackup.css
- src/Binovo/ElkarBackupBundle/Resources/public/js/edit-client.js
- src/Binovo/ElkarBackupBundle/Resources/views/Default/client.html.twig
This PR adds the possibility to customize the Rsnapshot "ssh-args" parameter directly from the Client configuration form.
Screenshots:
> Customize  SSH args into the Client advanced configuration (#87)

- app/DoctrineMigrations/Version20160429134626.php
- src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
- src/Binovo/ElkarBackupBundle/Entity/Job.php
- src/Binovo/ElkarBackupBundle/Form/Type/JobType.php
- src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php
- src/Binovo/ElkarBackupBundle/Resources/translations/BinovoElkarBackup.en.yml
- src/Binovo/ElkarBackupBundle/Resources/views/Default/job.html.twig
This PR removes "Owner" field from Job edition form and changes the "owner" checkbox to use "Client owner" instead.
More info: #139
> Remove "Owner" field from Job edition form (Fixes #139)

- src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
This PR make admin users able to list and sort all existing jobs. Currently only root user (id=1) can do that.
More info: #141
> Make admin users able to list and sort all existing jobs (fixes #141)

- debian/DEBIAN/postinst
This PR escapes special characters from db_name during the installation process. (fixes #212)
> Escape special chars from DB name (fixes #212)

- src/Binovo/ElkarBackupBundle/Command/StopJobCommand.php
Algunas veces cuando rsnapshot sale con status code diferente (ejemplo 2) o por algun error, el mismo rsnapshot borra el pid file o $lockfile y al poner "ABORT" el status queda siempre en "ABORTING" y nunca cambia, este fix resuelve que si no esta el $lockfile y tenemos el status de "ABORTING", asignemos el status de ABORTED, ya que el Job ya fue detenido con anterioridad.
Ejemplo de salida de rsnapshot:
touch /var/spool/elkarbackup/backups/0002/0011/Weekly.0/
rm -f /tmp/rsnapshot.0002_0011.pid
/usr/bin/logger -p user.info -t rsnapshot[4594] /usr/bin/rsnapshot -c \
rsnapshot.2_11.cfg Weekly: completed successfully
> Change status from ABORTING to ABORTED if the lockfile has been deleted

- src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php
This PR will limit the rsnapshot output if the command finishes with errors. It should fix issues #221 and #173 .
> Limit long command output

- src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
- src/Binovo/ElkarBackupBundle/Resources/views/Default/directory.html.twig
This PR fixes issue #159 .
Browsing a directory, if there is a symlink, it hiddes the option to follow it / download it.
> Do not follow/download symlinks

- src/Binovo/ElkarBackupBundle/Form/Type/UserType.php
- src/Binovo/ElkarBackupBundle/Resources/public/css/elkarbackup.css
This PR makes optional the passwords fields under the user edition. In this way, we can now edit any other field (i.e. email address) without type/change the password.
Related issue: #210
> Change password fields from required to optional

- src/Binovo/ElkarBackupBundle/Lib/BackupRunningCommand.php
This PR will:
- Fix an error related with an Array to String conversion
- Limit the output of script commands: very large outputs can provoke a MySQL error
> Fix array error and limit script output size

- .travis.yml
- README.md
- app/config/parameters.yml.travis
- src/Binovo/ElkarBackupBundle/Tests/Controller/DefaultControllerTest.php
This PR integrates the Travis CI service in Elkarbackup Github main repo.
It includes a stupid test to check that the login window is loading properly (`src/Binovo/ElkarBackupBundle/Tests/Controller/DefaultControllerTest.php`). I know, it doesn't look very useful. But at the same time it means that the installation stage is working correctly with different PHP versions (`5.5`, `5.6`,`7.0`, `7.1`,`7.2`):
- composer install
- symfony doctrine:database:create
- symfony doctrine:schema:create
- ...
Anyway, you're welcome to implement more tests.
> Integrate TravisCI

- app/DoctrineMigrations/Version20180207095757.php
This PR solves #282 issue.
The param value from _backup_dir_ is moved to the new Backup Location entity and removed from _parameters.yml_.
This way the parameter will be correctly moved to the database if the default directory had changed. If there is no _backup_dir_ param, a new Backup Location entity will be created with default values.
Anyway, the created Backup Location entity will be assigned to all jobs.
> Migration modified to migrate correctly backup_dir param.

- src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
- src/Binovo/ElkarBackupBundle/Resources/public/js/show-clients.js
This PR solves the log message that wrote 'QUEUED' multiple times when queuing a job. Now, when the job is queued multiple times, it shows a warning message. #294
> Added message when trying to queue same job multiple times.

- debian/DEBIAN/postinst
- makepackage.sh
The error was caused by an incorrect permissions in log directories. Changing the group to "root" solves the error.
By the way, now I make sure the directory `/var/log/elkarbackup/jobs` will be created in post-installation stage.
> Fix logrorate permissions issue (#279)

- .travis.yml
This PR changes Travis-CI configuration:
- `services: mysql` is now required
- PHP5.5 is not available anymore with `dist=xenial`. I've disabled it temporarily, until I find a better solution.
> Fix Travis-CI configuration: services mysql required

- src/Binovo/ElkarBackupBundle/Lib/BaseScriptsCommand.php
This PR fixes the bug introduced in v1.3.0 that affects ELKARBACKUP_URL envar value, in PRE and POST JOB levels.
#321
> Fix ELKARBACKUP_URL bug (#321)

- src/Binovo/ElkarBackupBundle/Controller/DefaultController.php
This PR solves the 500 internal server error in "/client/<id>/job/<id>/config"
> Fix incorrect call to getEffectiveDir method (#323)

- src/Binovo/ElkarBackupBundle/Command/RunJobCommand.php
This PR fixes the issue #326 
It modifies the RunJobCommand, which was initially designed to run -only- on demand jobs (running the lowest of all retains).
As v1.3.0 uses RunJobCommand also for scheduled jobs, we now need to adapt it in order to support both kind of executions; on demand ("_Enqueue now_" button in web UI) and scheduled jobs (which will run all the pending retains for a custom date/time). That's what this PR does.
Example job, with a default policy: daily, weekly, monthly enabled
- Scheduled job: it will run all the pending retains (Monthly->Weekly->Daily)
- Running the job using the "_Enqueue now_" button: will run only the lowest retain (Daily in this example)
_**Note** that after this change we cannot call run_job command directly from the CLI to run on demand tasks, as …
> Run all the runnable retains for scheduled jobs

- src/Binovo/ElkarBackupBundle/Command/TickCommand.php
This PR fixes the issue #328 
TickCommand checks for non-executable remaining jobs. However, the condition to check that situation is not correct as currently any scheduled backup job is sending that warning message at the end of the process.
```php
if ($queuedJobs == $queueCount && $noCandidate == false) {
$this->warn('There are jobs remaining but their configuration does not allow to execute them');
$noCandidate = true;
} else {
$noCandidate = false;
}
```
Keeping that in mind, I've updated the condition:
```php
if ($queuedJobs > 0 && $queuedJobs == $queueCount && $noCandidate == false) {
$this->warn('There are jobs remaining but their configuration does not allow to execute them');
$noCandidate = true;
} else {
$noCandidate = false;
}
```
However, I don't know how to provoke this …
> Fix jobs remaining warning message

- src/Binovo/ElkarBackupBundle/Command/RunJobCommand.php
This PR renews the DB connection after Rsnapshot command execution (if it's necessary).
More info: in some cases, MySQL connection dies after Rsnapshot execution (in RunJobCommand), causing the error described in #331
In v1.0.3 TickCommand was improved, renewing DB connection between commands to avoid these errors. However, we forgot RunJobCommand.
> Renew the DB connection after executing Rsnapshot

- debian/DEBIAN/control
Fixes #393 
Changed from "mysql-client" to "default-mysql-client" as dependency. We keep "mysql-client" as an alternative package name (pipe symbol)
> [Deb package] dependency changed to default-mysql-client

- CHANGELOG.md
- src/Binovo/ElkarBackupBundle/Resources/views/Default/logs.html.twig
Fixed path to download log files from error logs, url-prefix added, issue-313 resolved.
> Fix log-path to download log files #313

- .github/workflows/publish-deb-package.yml
This Github Action will build and upload the Debian package automatically when we create a new Release.
> Github action: build the deb package automatically

- migrations/Version20180207095757.php
- src/Migrations/LegacyBackupDirAwareInterface.php
Corrected 'backup_dir' parameter's name bug. 'backup_dir' was defined in trait and 'backupDir' was called.
> Correct bug, undefined parameter in migrations

- docker/entrypoint.sh
- docker/envars.sh
APP_ENV was named SYMFONY_ENV in previous versions and it was not updated. Now docker image is in prod environment by default.
> Correct parameter name APP_ENV. Fixes issue #470

- migrations/Version20210315133526.php
Changed statements to rename index since MariaDB 10.3 does not support RENAME INDEX statement. First dropped the foreign key and the index and create it with the new name instead. Fixes issue #479
> Change index rename statement when upgrading DB for MariaDB (Issue #479)

- CHANGELOG.md
- config/packages/security.yaml
- debian/changelog
- translations/BinovoElkarBackup.en.yml
This PR blocks login for users with USER role and updates user form side help.
Change is simple enough and allows us to make this breaking change for 2.0.0 easily.
If there are Elkarbackup admin out there that want to continue using USER roles, they can just adjust security.yaml to allow their login.
Closes #157
> Proposal for blocking users with USER role - Issue 157

- docker/Dockerfile
We're including them to our codebase, so we don't need to download them
Issue #482
> Dojo/jQuery download not required in Dockerfile

- docker/entrypoint.sh
- docker/envars.sh
If the user doesn't change the value of `SYMFONY__EB__SECRET` environment variable, entrypoint.sh will generate a new one.
We also should encourage users to change its value in the documentation.
Issue #503
> Generate the Symfony secret in Docker entrypoint

- config/services.yaml
- src/Controller/DefaultController.php
This should close #538 .
I'm not particularly fond of the sleep but I can't see how to wait properly. Without the sleep, sometimes the redirected form doesn't show updated values yet.
Also, constructor's first parameter $cacheDir is no longer needed, but I don't know where to unwire it :)
> Fix cache clear after changing parameters.

- tests/api/JobTest.php
If it is just checked the entity parameters the assertion will fail. Iri, id and type are also needed in the array.
> Get complete array to assert job is in the list

- src/Service/ClientService.php
- tests/api/ClientTest.php
Check if client name exists before persisting in DB and throw clear error message. Enhacement issued in #554 and fixes issue #564
> Improve error message when client name exists (#554)

- docker/README.md
- docker/docker-compose.yml
- docker/entrypoint.sh
This PR will set EB_CRON enabled by default.
If you don't want to have Tick command every minute with Cron, explicitly set the value to "disabled".
Fixes issue #576
> Docker: Cron enabled by default

- composer.json
- composer.lock
- docker/composer.json.docker
hautelook/alice-bundle is missing. It looks that the "official" alternative is the theofidry's fork. More info: #600
Should we wait before applying this fix to see if there is any other better solution? @elacunza
> alice-bundle is gone, use theofidry's fork instead

- composer.lock
Symfony/serializer updated to version 4.4.35 to avoid [CVE-2021-41270](https://www.cvedetails.com/cve/CVE-2021-41270/)
Fixes #621
> Update symfony/serializer from 4.4.20 to 4.4.35
